server:
  port: 8080

spring:
  # Configuração do MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/encurtador_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuração do JPA/Hibernate
  jpa:
    # AVISO DE TECH LEAD: Como estamos usando Flyway, o Hibernate não deve
    # criar ou alterar tabelas. Ele deve apenas 'validar' se o mapeamento do código bate com o banco.
    hibernate:
      ddl-auto: validate
    show-sql: true # Útil em dev para ver as queries geradas
    properties:
      hibernate:
        format_sql: true

  # Configuração do Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    # O Spring vai procurar os scripts SQL nesta pasta automaticamente
    locations: classpath:db/migration

  # Configuração do Redis
  data:
    redis:
      host: localhost
      port: 6379